### ISSUE TITLE
Show the run range used in the query after the JSON lists are retrieved 

### ISSUE THREAD

**Issue by mmusich** [ptrstn/lumis#1]
Title says it all, after clicking on show JSON, the memory of the initial run-range is lost. Would it be possible to show it ?
Thanks,
M. 
@tsusa

**Comment by ptrstn** [comment]
Yes, i'll implement it right away!

Would you also like to see the runs that were omitted because of missing lumisections?

**Comment by mmusich** [comment]
> Would you also like to see the runs that were omitted because of missing lumisections?

@ptrstn  not sure to understand. You mean missing lumisections from the no-quality json?

**Comment by ptrstn** [comment]
> > Would you also like to see the runs that were omitted because of missing lumisections?
> 
> @ptrstn not sure to understand. You mean missing lumisections from the no-quality json?

If a run contains only lumisections where the dcs flags are turned off, it will not be displayed in either the no quality flag json or the quality flag json.

For instance, for the run "324078" only empty JSON outputs are shown because the tracker components are "red" basically everywhere.

See:
https://lumis.web.cern.ch/?run_min=324078&run_max=324078
https://cmswbm.cern.ch/cmsdb/servlet/LumiSections?RUN=324078

**Comment by mmusich** [comment]
@ptrstn ah OK!
Can those runs / lumisections go into a fourth category (like DCS-off Lumisections)? We don't want to have the HV failures accounted for in certification efficiency, though it's an interesting information to have.

**Comment by mmusich** [comment]
@jandrea you might want to follow and have a say

**Comment by ptrstn** [comment]
> @ptrstn ah OK!
> Can those runs / lumisections go into a fourth category (like DCS-off Lumisections)? We don't want to have the HV failures accounted for in certification efficiency, though it's an interesting information to have.

Yes, I am adding an additional section to highlight runs that have been excluded due to DCS-off flags.
It will be for informational purposes only, regardless of brilcalc usage.

**Comment by mmusich** [comment]
Thanks a lot Peter!
